// <auto-generated />
namespace BikeFit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddManufacturerIsActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddManufacturerIsActive));
        
        string IMigrationMetadata.Id
        {
            get { return "201305241404393_AddManufacturerIsActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
